title: bergerb
subtitle: Adventures in Software Development and Life
author: Brent Berger
avatar_url: https://2.gravatar.com/avatar/b9a21f340f4d0b1a72356d69fda65571?s=160
# email: your-email@domain.com  # Comment out this line if you don't want to expose your email.
description: > # this means to ignore newlines until "twitter_username:"
  Technology, Software Development, and Life.
repository: bergerb/bergerb.github.com

# Google Analytics
#google_analytics: UA-

# contact
contact:
#  email: your-email@domain.com  # Comment out this line if you don't want to expose your email.

# social links
twitter_username: bergerb
github_username:  bergerb
rss: rss

# 
# Subscribe Feed
# 
# By default, your site generates a subscription feed (RSS/Atom) at /feed.xml
# Uncomment the next two lines to change the path.
feed:
   path: /atom.xml

# If you use a feed publisher such as Feedburner, uncomment the next line
#subscribe_rss: http://feeds.haacked.com/haacked

# Homepage
show_excerpts: true  # set to true to show excerpts on the homepage, otherwise full posts are shown

# Comments
# To enable comments, set the `enabled` field to true and supply either a Disqus short name or a Jekyll comments receiver
comments:
  enabled: true
  show_count: true
  disqus_shortname: bergerb
    

emptyArray: [] # Leave this here.

# haackbar date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
haackbar:
  date_format: "%b %-d, %Y"

#
# Jekyll Settings
#
permalink: /archive/:year/:month/:day/:title/
paginate: 5
page_group_size: 5 # number of pages to group by in the pagination.
paginate_path: "/archive/page/:num"
category_dir: categories

# Build settings
markdown: kramdown
kramdown:
  hard_wrap: false
remote_theme: haacked/haackbar

exclude: [README.md CODE_OF_CONDUCT.md script .gitattributes .gitignore keybase.txt RakeFile]
keep_files: [images demos code ads.txt robots.txt favicon.ico]
incremental: true

github: [metadata]

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache